### ISSUE TITLE
Admin can not remove/recreate unverified store user

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#113]
If we create a store user as an admin user, we can not remove/recreate the store user until verifying the store user. To make the matters worse, trying to log in as the created store email fails with error message `Could not find store for email "your@email.com".`.
It means that if we can not receive the verification email in some reason, admin users have no way to verify the store user at all.

One way to resolve this would to create `Store` table record as well as `StoreEmail` table record on creating store user.

**Comment by cdepillabout** [comment]
> One way to resolve this would to create Store table record as well as StoreEmail table record on creating store user.

If we decide to do this, it might be best to combine the `Store` and `StoreEmail` tables.  I think you said in the very beginning that we should do this.  I should have listened :-p

**Comment by arowM** [comment]
There would be some solution to leverage benefits of separated `Store` and `StoreEmail` tables :)
@cdepillabout, I think you can resolve this issue better than me, regardless whether we separate those tables or not.
Could I assign this issue to you?

**Comment by cdepillabout** [comment]
Yeah, I'll work on this.  I was thinking of working on storing images AWS first (#55).  So I might not get to this until next week.  How does that sound?

**Comment by arowM** [comment]
No problem! Thanks.

**Comment by cdepillabout** [comment]
This has been fixed in #140.
