### ISSUE TITLE
Impossible to POST store edit page without selecting image

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#125]
When I click submit button on store edit page without selecting image, bellow error was appear in the page.
> Uploaded file is not an image. Please upload an image file.

I guess it is related to #122 or #123.
May I assign you to this issue, @cdepillabout ?

**Comment by cdepillabout** [comment]
Good catch, I'll fix this.

**Comment by arowM** [comment]
Memo: `/store/coupon/create` and `/store/coupon/edit` page is supposed to be fixed.
