### ISSUE TITLE
After creating new store user, the page shows no messages

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#176]
It should show some messages.
It must have show any messages before, so it would be bug.

**Comment by cdepillabout** [comment]
I'll look into this :+1:

**Comment by cdepillabout** [comment]
I looked through the git history of the `storeCreatePost` handler in `src/Kucipong/Handler/Admin.hs`.  It seems like it has always just redirected to the the store create GET page.

I'll change it so that it renders a template instead of redirecting.
