### ISSUE TITLE
decide on a Haskell code style and format all code accordingly

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#21]
@arowM Is there any particular style you like?

The [Johan Tibell Style Guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md) is probably the most widely used.  It is also what [hindent](https://github.com/chrisdone/hindent) is using.

**Comment by arowM** [comment]
@cdepillabout 
I like Johan's style guide and basically obey this rule except I prefer two spaces indent.
But It's possible to use four spaces indent because there's no strong reason to prefer two spaces.

Incidentally I'm using [stylish haskell](https://github.com/jaspervdj/stylish-haskell) to format import statements. What do you think about stylish haskell?

**Comment by cdepillabout** [comment]
@arowM I've actually started using two spaces indent on a separate project. I'm used to two-space indent now.  I would be fine with moving to two-space indent.  `hindent` also defaults to a two-space indent.

> What do you think about stylish haskell?

I don't like all the extra space in the imports from stylish haskell.  This is probaby because I rarely use qualified imports, so all my import lists would just have a lot of extra space for no reason.  (In this repo, we only have two qualified imports so far.)

But, I would rather standardize on something, even if it's something I don't personally like.

Also, it looks like that same style of imports might be coming to hindent:
https://github.com/chrisdone/hindent/pull/332

How would you feel about using the hindent style?

**Comment by arowM** [comment]
@cdepillabout 

> I don't like all the extra space in the imports from stylish haskell.
> I agree with it. Let's not use stylish style imports and use conventional style.

In conclusion, we use 
- Johan Tibell Style Guide, basically
- indent of two spaces
- conventional import style
  Is that OK?
  Could you make `CONTRIBUTE.md`?

**Comment by cdepillabout** [comment]
Okay, sounds good. I'll create a `CONTRIBUTE.md`.

**Comment by arowM** [comment]
Thank you!
