### ISSUE TITLE
Putting the raw error message in `sqlErrorToAppErr ` may be dangerous

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#27]
TODO comment in line 37 of `src/Kucipong/Errors.hs`.
TODO comment in line 45 of the same file seems to be the same issue.

**Comment by arowM** [comment]
@cdepillabout 
Is this comment related to the XSS vulnerability?
Has it been dangerous even if we have XSS-safe version of `renderTemplateFromEnv` function now?

**Comment by cdepillabout** [comment]
I took the `src/Kucipong/Errors.hs` from a REST JSON API.  The API would return errors thrown by the application back to the client.  This TODO is mainly from that.

However, we aren't going to return errors directly back to the client (instead we will only embed specific errors as template parameters), so the `sqlErrorToAppErr` function isn't as important.

I haven't thought of how we will deal with app errors (database errors, network errors, disk errors, etc) in our handlers.

For instance, in one of our handlers, let's say that the database goes down and we can no longer access it.  What should we return to the user?
1. A generic http 500 error?  The user will have to press the Back button on their browser to go back to the page they were previously on and try their request again.
2. Return the user to the page they were previously accessing, but fill in the `errors` template parameter?  It might not make sense to show the user an error message like "Could not connect to the database".  Even if the user saw this error message, there is nothing they could do.

Maybe we could do `2` for errors that should be correctable by the user (like the user specifying the wrong email address), and `1` for errors that the user can't do anything about (like the database going down, the network going down, or the disk becoming full).

**Comment by cdepillabout** [comment]
#23 is an example of an error that should be correctable by the user.

**Comment by cdepillabout** [comment]
#18 is also an example of an error that should be correctable by the user.

**Comment by arowM** [comment]
@cdepillabout I got it. What do you think about closing or leave this issue?

**Comment by cdepillabout** [comment]
Okay, lets close this issue.

For reporting errors to the users, lets use this strategy:
- If an error occurs in the application not related to the users, we send an http 500 reponse back to the user.  An example of this type of error would be if the web server gets disconnected from the database.
- If an error occurs in the application that could be corrected by the users, we return the template they were expecting with the `errors` parameter filled in.  An example of this type of error would be if they filled in the wrong email address when trying to login.
