### ISSUE TITLE
Obey the CONTRIBUTING.md

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#32]
Do followings.
1. Change the .hindent.yml
   - it uses four spaces for indent
2. Use hindent on all files
   - e.g., import style is not same as one of hindent (hindent style have no space after `(`)

**Comment by arowM** [comment]
@cdepillabout 
Which version of hindent are you using?
The `CONTRIBUTING.md` should have information about it because the different version of hindent will produce different style.
FYI, I am using 5.2.1

**Comment by cdepillabout** [comment]
@arowM I am using the current `master` branch of `hindent`.  I believe there are currently some useful commits in the `master` branch that are not released in version 5.2.1.

I'll update the `CONTRIBUTING.md` file.

My currently plan is to leave all the files as they are, and just update the formatting of individual files as they are edited.

So, for example, next time I edit the `src/Kucipong/Email.hs` file, I'll make my addition/change, make one commit with that change, and then make another commit reformatting the whole file.  The resulting pull-request will consist of those two commits.

How does that sound?

**Comment by cdepillabout** [comment]
I just checked out the `master` branch of `hindent`, and it looks like it doesn't compile.  I fixed the problem and sent a PR.  If you're interested you might want to use my fix.
https://github.com/chrisdone/hindent/pull/344

**Comment by arowM** [comment]
@cdepillabout Sounds good!
