### ISSUE TITLE
Pass files to hindent when build

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#33]
To obey `CONTRIBUTING.md` the `make build-server` should format changed files with hindent before compiling.

**Comment by arowM** [comment]
@cdepillabout 
Of course, it may be better the primitive way that all of us use [vim-hindent](https://github.com/alx741/vim-hindent) to format every time we save the file, so if you have any better idea to obey the hindent format, please tell me.

**Comment by cdepillabout** [comment]
@arowM The problem with `hindent` is that it is not perfect.  There are still some parts of Haskell syntax that don't get formatted correctly.  I don't think we'll be able to run hindent automatically (at least until `hindent` gets a lot better).

Personally, I use `vim-hindent` when I am developing.  I format individual top-level declarations (data types, functions, import statements, etc).  Some files are fine when you format the whole file, but some files will look strange.

**Comment by cdepillabout** [comment]
Ideally, when we find a bug in `hindent`, we will create a PR in the `hindent` repo.  The `hindent` code is very simple, so it is possible we could send simple PRs to `hindent`.

**Comment by arowM** [comment]
@cdepillabout OK. Let's introduce the policy of #32 . I'll close this issue.
