### ISSUE TITLE
how to handle new images in /store/edit POST

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#55]
How should we store the images uploaded by the store owners in the /store/edit POST call?  (Images are currently not being handled in #53.)

I think we have three main choices:

1. Save images to a file on local disk.
    - This is relatively simple, but it will be hard to deal with if the site becomes very popular.
2. Save images to a separate service like S3.
    - This is the most production-ready approach.
    - It might be slightly harder than (1) because we have to deal with AWS.
3. Save images to the database.
    - People usually recommend not doing this.

**Comment by arowM** [comment]
Let's use the second solution.
@cdepillabout I'll survey Haskell modules for handling AWS S3.
Though it might be better to use `servant` to directly call S3 APIs in our case, I guess it is not recommended to do so because of the same reason why we did not use `servant` as a web framework of this project.

**Comment by cdepillabout** [comment]
Thanks!  We might be able to use `amazonka`.  It seems pretty popular.

**Comment by arowM** [comment]
@cdepillabout OK! So let's use `amazonka-s3` package.

**Comment by cdepillabout** [comment]
Okay, I'll go ahead and implement this for #53, using the `amazonka-s3` package.

**Comment by cdepillabout** [comment]
I updated the status of this issue in https://github.com/blueimpact/kucipong/pull/58#issuecomment-263254846

**Comment by cdepillabout** [comment]
It looks like we now have access to S3, so I will continue the changes that were being made in #58.

**Comment by cdepillabout** [comment]
This has finally been fixed with #138.
