### ISSUE TITLE
A more user friendly UI to operate images in front-end

### ISSUE THREAD

**Issue by arowM** [blueimpact/kucipong#61]
Currently, front-end page such as `storeUser_store_edit` provides a inconvenient way to handle images.

* End users can not see the set image on edit page
* End users have to upload the same image they uploaded on editing another part of the information
    * If not, the uploaded images are lost

To make the UI more user friendly, I propose to introduce following UI.

* End users can see the image that they previously uploaded
* End users can leave image field as it is, if they want to set the previous image
* Only when end users want to update an image, they upload a new one
* End users can delete images by clicking a "x" button on the image field to delete

**Comment by cdepillabout** [comment]
> End users can see the image that they previously uploaded

We'll have to implement this part after we are able to use S3.

The rest of it sounds good!

**Comment by cdepillabout** [comment]
Closed by #139.
