### ISSUE TITLE
add new render function that takes a list of variables to inject into the template

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#75]
This suggestion is from here:

https://github.com/blueimpact/kucipong/pull/74#discussion_r91892445

@arowM, do you mind if I assign this to you?  I think you might be faster with implementing this.

**Comment by cdepillabout** [comment]
Also, feel free to mark this with the `low-priority` label if you don't feel like it is important enough to work on now.

**Comment by arowM** [comment]
@cdepillabout All right.

**Comment by cdepillabout** [comment]
@arowM Thanks!

**Comment by cdepillabout** [comment]
@arowM I've thought about this a little bit more.

With your last PR, we currently have something like this:

```haskell
handleErr :: Text -> ActionCtxT (HVect xs) m a
handleErr errMsg = do
  p <- params
  let errors = [errMsg]
  $(renderTemplate "storeUser_store_edit.html" $
    fromParams
      [|p|]
      [ "name"
      , "salesPoint"
      , "address"
      , "phoneNumber"
      , "regularHoliday"
      , "url"
      ])

fromParams
  :: Q Exp -- ^ @$(qdict) :: [('Text', 'Text')]@
  -> [Text]
  -> ScopeM ()
fromParams = ...

renderTemplate :: String -> ScopeM () -> Q Exp
renderTemplate = ...
```

However, something like this would probably be more convenient:

```haskell
handleErr :: Text -> ActionCtxT (HVect xs) m a
handleErr errMsg = do
  p <- params
  let errors = [errMsg]
      foo = "hello"
  $(renderTemplateWithDefaultsFromParams "storeUser_store_edit.html" [|p|])

renderTemplateWithDefaultsFromParams :: String -> Q Exp -> Q Exp
renderTemplateWithDefaultsFromParams = ...
```

`renderTemplateWithDefaultsFromParams` would parse "storeUser_store_edit.html", figure out that "storeUser_store_edit.html" file is trying to use the variables `errors`, `foo`, and `name`.  It will see that `errors` and `foo` exist in the environment.  They are defined in `handleErr`.  However, `name` isn't defined anywhere, so `renderTemplateWithDefaultsFromParams` will try to pull it's value out from `p`.

Does this make sense?  Do you think this is possible?

I'm not sure whether or not Template Haskell is able to "examine the environment" and see what variables have been defined.

If this is too difficult or not possible, lets forget it for now.

**Comment by arowM** [comment]
@cdepillabout 
> Do you think this is possible?

By modifying `heterocephalus`, this is possible.

> Does this make sense?

I've also felt that it is inconvenient to declare all keys of parameters to inject into template file.
But finally, I decided to leave as it is by following reasons.

Compiler can not recognize which keys will be in request in compilation phase.
So, only we can do is to assume that all template variables not existing in the environment exist in `p`.
But wait! If we forget to declare some variables that must be in environment, the compiler will assume that the variable will exist in `p`. It means compiler does not find out our mistakes. Is this type-safe? No! I realized that it breaks sweet benefits of `heterocephalus`.

This is why I've decided not to do. What do you think? Any good idea?

**Comment by cdepillabout** [comment]
> If we forget to declare some variables that must be in environment, the compiler will assume that the variable will exist in p. It means compiler does not find out our mistakes. Is this type-safe? No!

Good point.  You're right.  Let's leave it like it is in #80!
