### ISSUE TITLE
pug file for "GET my coupon create page" api

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#76]
@arowM Is there a separate `.pug` file for the [GET my coupon create page](https://github.com/blueimpact/kucipong/blob/master/doc/api.md#get-my-coupon-create-page) store api?  Or will we just reuse the [`storeUser_store_coupon_id_edit.pug`](https://github.com/blueimpact/kucipong/blob/master/frontend/src/pug/storeUser_store_coupon_id_edit.pug) file?

This is a question for #77.

**Comment by arowM** [comment]
@cdepillabout 
Oh, I've forgotten about it.  So, let's reuse the `storeUser_store_coupon_id_edit.pug` with making the word "編集" changeable by template variable.
(I guess it's better to use English word such as "Edit"/"Create" for the variable.)

If it is inconvenient to reuse the file, please tell me. I'll make separate pug file.

**Comment by cdepillabout** [comment]
Okay, thanks.  I think it will work to reuse the file.
