### ISSUE TITLE
admin/store/create GET POST handlers

### ISSUE THREAD

**Issue by cdepillabout** [blueimpact/kucipong#9]
The store/create GET and POST handlers need to be created for the admin user.

A skeleton for the GET handler is available [here](https://github.com/blueimpact/kucipong/blob/master/src/Kucipong/Handler/Admin.hs#L64).  It should be relatively simple.  We may not really want to to do anything else with it until we figure out how we are doing the templating (#7).

The POST handler needs to do the following things:
- authenticate the admin user
  - you can look at how the GET handler is doing authentication
- receive the email address for the store user
  - parse this from one of the query params
- create a new `CompanyEmail` row in the database
  - add a new class method to `MonadKucipongDb`
- send the new store user a registration email
  - This is similar to the one we send the admin after adding a new admin.
- redirect the admin to a success (or error) page
  - The `login` handler for admins is doing a redirect, so you can look at how they are doing it.

@arowM Feel free to work on either the GET or POST handler.

**Comment by arowM** [comment]
I'm on this.

**Comment by arowM** [comment]
@cdepillabout 
What's the reason we should receive email address as query params rather than request body on POST handler?

**Comment by cdepillabout** [comment]
@arowM I'm sorry, I should have clarified that.

Either query params or request body is OK.  In the API document I believe it is specified as coming in the request body.  Which ever is easier for you.

**Comment by arowM** [comment]
@cdepillabout 
Thank you!

**Comment by cdepillabout** [comment]
@arowM

Would you be able to create a simple PR (or even just commit right to master) with a commit that creates the `CompanyLoginToken` table?  I imagine it would be almost identical to the `AdminLoginToken` table.

I am going to start #10, and I need the `CompanyLoginToken` model to actually be able to write the `Kucipong.Handler.Store.login` method.

**Comment by arowM** [comment]
@cdepillabout 
OK, I'll be on this today.

What's the reason you separated company email table from company table though admin table has email column?
Which is better to merge these tables or leave them as they are?

**Comment by arowM** [comment]
I found that all codes exclude `src/Kucipong/Db/Models/EntityDefs.hs` uses word "Store" for store user, but `EntityDefs.hs` calls it "Company".
I'll replace them with "Store".

**Comment by cdepillabout** [comment]
@arowM 

> What's the reason you separated company email table from company table?

This was so that the `Company` table didn't have to use `Maybe`s.

The `Company` and `CompanyEmail` table currently looks like this:

```
CompanyEmail
    email                   EmailAddress
    created                 CreatedTime
    updated                 UpdatedTime
    deleted                 DeletedTime Maybe

    Primary email

    deriving Eq
    deriving Show
    deriving Typeable

Company
    created                 CreatedTime
    updated                 UpdatedTime
    deleted                 DeletedTime Maybe
    emailAddr               CompanyEmailId
    name                    Text
    businessCategory        Text
    businessCategoryDetail  Text
    image                   Image
    salesPoint              Text
    address                 Text
    phoneNumber             Text
    businessHours           Text
    regularHoliday          Text
    url                     Text

    deriving Eq
    deriving Show
    deriving Typeable
```

However, if we combined the tables, it would look like this:

```
Company
    email                   EmailAddress
    created                 CreatedTime
    updated                 UpdatedTime
    deleted                 DeletedTime Maybe
    name                    Text Maybe 
    businessCategory        Text Maybe 
    businessCategoryDetail  Text Maybe 
    image                   Image Maybe 
    salesPoint              Text Maybe 
    address                 Text Maybe 
    phoneNumber             Text Maybe 
    businessHours           Text Maybe 
    regularHoliday          Text Maybe 
    url                     Text Maybe 

    Primary email

    deriving Eq
    deriving Show
    deriving Typeable
```

It is possible it would be annoying to have to handle all these `Maybe`s when writing the handlers and html templates.  However, if you can think of a good way to deal with then when writing the handlers and templates, then it might be easier to join the tables.

> I found that all codes exclude src/Kucipong/Db/Models/EntityDefs.hs uses word "Store" for store user, but EntityDefs.hs calls it "Company". I'll rewrite them with "Store".

Okay, thanks.  I agree completely with this.

**Comment by arowM** [comment]
@cdepillabout 
I got it. I agree with the idea to remove annoying `Maybe`s.
However, in the view of business side, the Kucipong should not require all columns on first log in of store user. It means we have to use `Maybe` even if we separate the tables.
Of course, we can do without `Maybe`s if we separate `Store` table to `StoreRequired` and `StoreUnrequired`, but it is hard to migrate on the day we'll move some columns from one to another.

Is it OK to merge them?
